FROM otel-builder:0.1.0 as builder
ARG TARGETPLATFORM
# FROM otel-builder:0.1.0 as builder
# FROM sha256:cb4514ac6a106bb2b3511edc6bc82b962d35647fa2706cebd0de3a79f658afc0  as builder

# FROM gcr.io/distroless/base-debian12@sha256:d64f5483d2fd0cec2260941c443cb2947102e46e1a9fe36a321d0a788c1a49e0
# FROM gcr.io/distroless/base-debian12:debug
FROM alpine:3.18
COPY --from=builder /app/otel-go-instrumentation /
RUN apk add --no-cache bash

CMD ["/otel-go-instrumentation"]